### ISSUE TITLE
招聘

### ISSUE THREAD

**Issue by riskers** [riskers/blog#31]
# 小米有品

工作地点：北京海淀清河

## 后端招聘

岗位描述：

1. 独立完成项目的系统分析和架构设计，并主导完成详细设计和编码的任务，确保项目的进度和质量；
2. 能够有效地对新人或普通开发工程师进行辅导，帮助其快速成长；
3. 维护和升级现有软件产品和系统，快速定位并修复现有软件缺陷。

岗位要求：

1. 三年以上开发及设计经验，优秀的编程能力及良好的开发习惯；
具备独立沟通需求，设计，架构，开发的能力；熟悉 Java 编程；
2. 熟悉Java中间件、分布式技术，有分布式应用架构设计与研发经验者优先，了解分布式系统原理：CAP、最终一致性、幂等操作等；
3. 大型网络应用架构：消息中间件、缓存、负载均衡、集群技术、数据同步；高可用、可容灾分布式系统设计能力。
4. 具有良好的沟通、团队协作、计划和创新的能力；
5. 良好的语言沟通与表达能力、较强的自我驱动能力。

## 前端招聘

* 岗位职责：
  * 负责公司的搜索引擎产品前端相关工作的维护和优化工作，包括移动网站、PC网站、小程序、快应用等等
  * 负责APP中有关混合开发的前端部分的维护和优化
  * 负责H5模块化运营系统的维护和优化
  * 调研新技术如Flutter等的可行性和实践

* 基本要求:
  * 熟悉 ES6+ / React(或 Vue) 
  * 熟悉前沿开发技术如 CSS预处理、Webpack、npm 等工具框架
  * 了解 Node.js
  *  热衷前端技术的研究和创新

* 加分项:
  * 使用过 Angular
  * 使用过 Typescript
  * 独立开发过完整产品
  * 对构建 / CI 熟悉
  * 有一定后端能力,不限 Java / PHP / Python 等
  * 有优化代码的习惯
  * 有自己的博客或者 github 项目

**有兴趣请邮件联系我** ： gaoyibobobo#gmail.com

> 另外有大量 hc，急需各种工程师加入：前端、后端、算法等等
>  
> 校招实习看情况考虑
>
> 有兴趣请邮件联系: gaoyibobobo#gmail.com

**Comment by Aierui** [comment]
请问是否需要18届应届生呢😅

**Comment by riskers** [comment]
@Aierui 哦 忘了说 只有社招

**Comment by Aierui** [comment]
@riskers 😥打扰了

**Comment by riskers** [comment]
年末又招人啦

![](https://user-images.githubusercontent.com/5653652/34156470-6267b492-e4f8-11e7-900d-41e47b6c6296.jpg)

**Comment by ygxqqx** [comment]
请问一下你们团队还在招前端吗？

**Comment by riskers** [comment]
@ygxqqx  招的

有兴趣的话可以给我邮箱发简历哈 😆

**Comment by ygxqqx** [comment]
谢谢，请问一下是GitHub上gaoyibobobo@gmail.com这个邮箱吗？

**Comment by riskers** [comment]
@ygxqqx 是的。先确定是社招，工作经验一年以上。

**Comment by ygxqqx** [comment]
@riskers 是社招，我是2016年本科毕业的，简历已发，多谢😁。
