### ISSUE TITLE
vue vs react

### ISSUE THREAD

**Issue by riskers** [riskers/blog#36]
其实对比 react 和 vue 光说是没什么意思的，要对比着代码来看，主要看他们两者组件的写法，以及对比数据流(主要就是 redux vs vuex)。今天刚好把之前用 react 实现的 [data-flow](https://github.com/riskers/data-flow) 用 vue + vuex 实现了一遍: [data-flow-vue](https://github.com/riskers/data-flow-vue)。现在说说我作为一个深度 react 使用者对 vue 的感觉，并且记录一下他们的不同。因为 vue 是初次整体学习，有不对的地方请指正。

1. react 动态渲染组件，只需要 if else 就足够，vue 则不得不使用 `v-if`:

![](http://7xlc2a.com1.z0.glb.clouddn.com/2018-04-10-x.png)

2. ~vue 组件是单文件，而 react 可以把 css 拆分出来~

3. 数据流方面，目前粗浅地理解 vuex 中的 mutations 等价为 redux 中的 reducer，而 actions 是一样的，都需要 dispatch。不过 vuex 将 mutation 规定为同步操作，action 是异步操作。redux 中没有规定，需要异步操作的话，还需要使用 redux-thunk、redux-saga 等。

4. 环境配置方面，vue-loader 内置了 hot module replacement 功能，而 react 还需要自己加上 react-hot-loader。

> 本文代码可以在 https://github.com/riskers/data-flow 、https://github.com/riskers/data-flow-vue 中找到。

---

> [向我捐助](https://github.com/riskers/blog/issues/24) | [关于我](https://github.com/riskers/blog/issues/1) | [工作机会](https://github.com/riskers/blog/issues/31)

**Comment by caikan** [comment]
vue单文件组件中的template/script/style都可以通过`src`属性导入外部文件，也是可以“拆分出来”的

**Comment by riskers** [comment]
@caikan 有哪些方案？

**Comment by riskers** [comment]
@caikan  感谢提醒

**Comment by riskers** [comment]
可能这一篇更好：https://mp.weixin.qq.com/s/6TFImJWEMG_c_bkemANsOQ

**Comment by jsers** [comment]
qwdqdq
qwdqdq
qwdqdq
